import { __ } from '@wordpress/i18n';

/**
 * Updates the value of a mission's hidden avatar field to the selected image id.
 *
 * @param {int} id
 * @param {string} missionId The id value of the current mission.
 */
const updateHiddenField = ( id, missionId ) => {
  const field = document.getElementById( `slo-avatar-${missionId}` );

  field.value = id;
};

/**
 * Gets the selected image from the media library and uses it to set the hidden field value.
 *
 * @param {Object} frame The media uploader frame generated by the WordPress media library.
 * @param {string} missionId The id value of the current mission.
 */
const onClose = ( frame, missionId ) => {
  const selection = frame
    .state()
    .get( 'selection' )
    .first();

  const id = selection?.attributes?.id;

  updateHiddenField( id, missionId );
};

/**
 * When the media uploader frame is open, select the image with the id stored in the mission's hidden field.
 *
 * @param {Object} frame The media uploader frame generated by the WordPress media library.
 * @param {string} missionId The id value of the current mission.
 */
const onOpen = ( frame, missionId ) => {
  const field = document.getElementById( `slo-avatar-${missionId}` );

  const selection = frame.state().get( 'selection' );

  if ( field.value && field.value !== 'undefined' ) {
    const { media } = window.wp;

    const attachment = media.attachment( field.value );

    attachment.fetch();

    selection.add( attachment ? [attachment] : [] );
  } else {
    selection.add( [] );
  }
};

/**
 * Loads the media library uploader frame.
 *
 * @param {Event} e A click event object.
 * @param {string} id The id value of the current mission.
 */
export const mediaUploader = ( e, id ) => {
  e.preventDefault();

  const { media } = window.wp;

  let imageFrame;

  if ( imageFrame ) {
    imageFrame.open();
  }

  imageFrame = media( {
    button: {
      text: __( 'Use as mission avatar', 'gpalab-slo' ),
    },
    library: {
      type: 'image',
    },
    multiple: false,
    title: __( 'Add an avatar', 'gpalab-slo' ),
  } );

  imageFrame.on( 'close', () => onClose( imageFrame, id ) );

  imageFrame.on( 'open', () => onOpen( imageFrame, id ) );

  imageFrame.open();
};
