<?php
/**
 * Registers the SLO class.
 *
 * @package SLO
 * @since 0.0.1
 */

 /**
  * Register all hooks to be run by the plugin.
  *
  * @package SLO
  */
class SLO {

  /**
   * The loader that's responsible for maintaining and registering all hooks that power the plugin.
   *
   * @var SLO_Loader $loader    Maintains and registers all hooks for the plugin.
   *
   * @access protected
   * @since 0.0.1
   */
  protected $loader;

  /**
   * The unique identifier and version of this plugin.
   *
   * @var string $plugin_name
   *
   * @access protected
   * @since 0.0.1
   */
  protected $plugin_name;

  /**
   * The version of this plugin.
   *
   * @var string $version
   *
   * @access protected
   * @since 0.0.1
   */
  protected $version;

  /**
   * Define the core functionality of the plugin.
   *
   * Set the plugin name and the plugin version that can be used throughout the plugin.
   * Load the dependencies and set the hooks for the admin area and
   * the public-facing side of the site.
   *
   * @since 0.0.1
   */
  public function __construct() {
    $this->plugin_name = $this->load_constants()->plugin_name;
    $this->version     = $this->load_constants()->version;
    $this->load_dependencies();
    $this->define_admin_hooks();
    $this->define_public_hooks();
  }

  /**
   * Import the constant values used to initialize the plugin's classes.
   *
   * @return SLO_Constants
   *
   * @since 0.0.1
   */
  private function load_constants() {
    // Defines the plugin name and version.
    require_once GPALAB_SLO_DIR . 'class-constants.php';

    return new SLO\Constants();
  }

  /**
   * Load the required dependencies for this plugin.
   *
   * Include the following files that make up the plugin:
   *
   * - SLO\Loader. Orchestrates the hooks of the plugin.
   * - SLO\Admin. Defines all hooks for the admin area.
   * - SLO\Frontend. Defines all hooks for the public side of the site.
   *
   * Create an instance of the loader which will be used to register the hooks with WordPress.
   *
   * @access private
   * @since 0.0.1
   */
  private function load_dependencies() {
    // The class responsible for orchestrating the actions and filters of the core plugin.
    require_once GPALAB_SLO_DIR . 'includes/class-loader.php';

    $this->loader = new SLO\Loader();

    // The class responsible for defining all actions that occur in the admin area.
    require_once GPALAB_SLO_DIR . 'admin/class-admin.php';
    require_once GPALAB_SLO_DIR . 'admin/class-ajax.php';
    require_once GPALAB_SLO_DIR . 'admin/class-cpt.php';
    require_once GPALAB_SLO_DIR . 'admin/class-cpt-list.php';
    require_once GPALAB_SLO_DIR . 'admin/class-dashboard.php';
    require_once GPALAB_SLO_DIR . 'admin/class-permissions.php';
    require_once GPALAB_SLO_DIR . 'admin/class-settings.php';
    require_once GPALAB_SLO_DIR . 'admin/class-ure.php';
    require_once GPALAB_SLO_DIR . 'admin/class-validation.php';

    // The class responsible for defining all actions that occur in the public-facing side of the site.
    require_once GPALAB_SLO_DIR . 'public/class-frontend.php';
    require_once GPALAB_SLO_DIR . 'public/class-template.php';
  }

  /**
   * Register all of the hooks related to the admin area functionality of the plugin.
   *
   * @since 0.0.1
   */
  private function define_admin_hooks() {
    $plugin_admin      = new SLO\Admin( $this->get_plugin_name(), $this->get_version() );
    $plugin_ajax       = new SLO\Ajax( $this->get_plugin_name(), $this->get_version() );
    $plugin_cpt        = new SLO\CPT( $this->get_plugin_name(), $this->get_version() );
    $plugin_cpt_list   = new SLO\CPT_List( $this->get_plugin_name(), $this->get_version() );
    $plugin_dashboard  = new SLO\Dashboard( $this->get_plugin_name(), $this->get_version() );
    $plugin_roles      = new SLO\Permissions( $this->get_plugin_name(), $this->get_version() );
    $plugin_settings   = new SLO\Settings( $this->get_plugin_name(), $this->get_version() );
    $plugin_ure        = new SLO\URE( $this->get_plugin_name(), $this->get_version() );
    $plugin_validation = new SLO\Validation( $this->get_plugin_name(), $this->get_version() );

    // Admin hooks.
    $this->loader->add_action( 'init', $plugin_admin, 'register_admin_scripts_styles' );
    $this->loader->add_action( 'init', $plugin_admin, 'register_slo_mission_meta' );
    $this->loader->add_action( 'admin_notices', $plugin_admin, 'localize_admin_script_globals' );
    $this->loader->add_action( 'pre_get_posts', $plugin_admin, 'exclude_autogenerated_pages' );

    // Ajax hooks.
    $this->loader->add_action( 'wp_ajax_gpalab_add_slo_mission', $plugin_ajax, 'handle_mission_addition' );
    $this->loader->add_action( 'wp_ajax_gpalab_remove_slo_mission', $plugin_ajax, 'handle_mission_removal' );
    $this->loader->add_action( 'wp_ajax_gpalab_slo_user_mission', $plugin_ajax, 'handle_user_mission_selection' );
    $this->loader->add_action( 'wp_ajax_gpalab_update_slo_permalink', $plugin_ajax, 'handle_permalink_update' );

    // Custom post type hooks.
    $this->loader->add_action( 'init', $plugin_cpt, 'gpalab_slo_cpt', 0 );
    $this->loader->add_action( 'init', $plugin_cpt, 'register_archive_status' );
    $this->loader->add_action( 'add_meta_boxes', $plugin_cpt, 'gpalab_slo_custom_meta' );
    $this->loader->add_action( 'save_post', $plugin_cpt, 'gpalab_slo_meta_save' );
    $this->loader->add_action( 'do_meta_boxes', $plugin_cpt, 'gpalab_slo_image_meta_box' );
    $this->loader->add_filter( 'post_type_link', $plugin_cpt, 'gpalab_slo_filter_permalink', 10, 2 );
    $this->loader->add_filter( 'single_template', $plugin_cpt, 'preview_link_template' );
    $this->loader->add_filter( 'preview_post_link', $plugin_cpt, 'hijack_slo_preview' );
    $this->loader->add_action( 'admin_head', $plugin_cpt, 'hide_unused_elements' );
    $this->loader->add_filter( 'post_updated_messages', $plugin_cpt, 'social_link_updated_messages', 10, 1 );
    $this->loader->add_action( 'admin_bar_menu', $plugin_cpt, 'remove_view_from_admin_bar', 999 );
    $this->loader->add_action( 'post_submitbox_misc_actions', $plugin_cpt, 'add_archived_to_status_dropdown' );

    // Hooks to manage the All Links page.
    $this->loader->add_action( 'manage_gpalab-social-link_posts_custom_column', $plugin_cpt_list, 'populate_custom_columns', 10, 2 );
    $this->loader->add_filter( 'manage_edit-gpalab-social-link_columns', $plugin_cpt_list, 'add_custom_columns' );
    $this->loader->add_filter( 'manage_edit-gpalab-social-link_sortable_columns', $plugin_cpt_list, 'make_custom_columns_sortable' );
    $this->loader->add_action( 'restrict_manage_posts', $plugin_cpt_list, 'add_mission_filter_dropdown' );
    $this->loader->add_filter( 'parse_query', $plugin_cpt_list, 'filter_social_links_by_mission' );
    $this->loader->add_filter( 'post_row_actions', $plugin_cpt_list, 'edit_link_actions', 10, 2 );
    $this->loader->add_action( 'load-edit.php', $plugin_cpt_list, 'handle_archive_link' );
    $this->loader->add_filter( 'bulk_actions-edit-gpalab-social-link', $plugin_cpt_list, 'add_custom_bulk_actions' );
    $this->loader->add_filter( 'handle_bulk_actions-edit-gpalab-social-link', $plugin_cpt_list, 'handle_bulk_archive', 10, 3 );
    $this->loader->add_action( 'admin_notices', $plugin_cpt_list, 'show_archive_notice' );

    // Adds a widget to the WordPress user dashboard.
    $this->loader->add_action( 'wp_dashboard_setup', $plugin_dashboard, 'slo_dashboard_widget' );
    $this->loader->add_action( 'admin_enqueue_scripts', $plugin_dashboard, 'enqueue_widget_scripts' );

    // Settings page hooks.
    $this->loader->add_action( 'admin_menu', $plugin_settings, 'add_settings_page' );
    $this->loader->add_action( 'admin_init', $plugin_settings, 'populate_settings_page' );
    $this->loader->add_action( 'admin_enqueue_scripts', $plugin_settings, 'enqueue_slo_admin' );
    $this->loader->add_filter( 'plugin_action_links_social-link-optimizer/social-link-optimizer.php', $plugin_settings, 'add_settings_link' );

    // User roles and permissions hooks.
    $this->loader->add_action( 'wp_before_admin_bar_render', $plugin_roles, 'slo_archive_remove_admin_bar_edit_link' );
    $this->loader->add_filter( 'page_row_actions', $plugin_roles, 'disable_actions', 10, 2 );
    $this->loader->add_filter( 'get_edit_post_link', $plugin_roles, 'remove_row_title_link', 10, 3 );

    // Check if the User Role Editor is active.
    $is_ure_installed = in_array(
      'user-role-editor/user-role-editor.php',
      apply_filters( 'active_plugins', get_option( 'active_plugins' ) ),
      true
    );

    // User Role Editor compatibility hooks.
    if ( $is_ure_installed ) {
      $this->loader->add_filter( 'ure_capabilities_groups_tree', $plugin_ure, 'add_custom_group', 10, 1 );
      $this->loader->add_filter( 'ure_custom_capability_groups', $plugin_ure, 'get_plugin_caps', 10, 2 );
    }

    // Required form fields validation hooks.
    $this->loader->add_action( 'init', $plugin_validation, 'register_validation_scripts_styles' );
    $this->loader->add_action( 'admin_enqueue_scripts', $plugin_validation, 'enqueue_slo_validation' );
  }

  /**
   * Register all of the hooks related to the public-facing functionality
   *
   * @since 0.0.1
   */
  private function define_public_hooks() {
    $plugin_frontend = new SLO\Frontend( $this->get_plugin_name(), $this->get_version() );
    $plugin_template = new SLO\Template( $this->get_plugin_name(), $this->get_version() );

    // Frontend hooks.
    $this->loader->add_action( 'wp_enqueue_scripts', $plugin_frontend, 'gpalab_slo_styles_scripts', 100 );

    // AJAX hooks.
    $this->loader->add_action( 'wp_ajax_gpalab_slo_load_more', $plugin_frontend, 'gpalab_slo_load_more' );
    $this->loader->add_action( 'wp_ajax_nopriv_gpalab_slo_load_more', $plugin_frontend, 'gpalab_slo_load_more' );

    // Hooks needed to utilize the SLO page template.
    $this->loader->add_filter( 'template_include', $plugin_template, 'view_project_template' );
  }

  /**
   * Run the loader to execute all of the hooks with WordPress.
   *
   * @since 0.0.1
   */
  public function run() {
    $this->loader->run();
  }

  /**
   * The reference to the class that orchestrates the hooks with the plugin.
   *
   * @return SLO_Loader    Orchestrates the hooks of the plugin.
   *
   * @since 0.0.1
   */
  public function get_loader() {
    return $this->loader;
  }

  /**
   * Retrieve the name of the plugin.
   *
   * @since 0.0.1
   */
  public function get_plugin_name() {
    return $this->plugin_name;
  }

  /**
   * Retrieve the version number of the plugin.
   *
   * @since 0.0.1
   */
  public function get_version() {
    return $this->version;
  }
}
